spring:
  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/oauth/google/callback
            client-id: 302908425383-gir2air2agv9vfu784t4265jki2kg8mv.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://travelplanner.c90ycbubgo4h.ap-northeast-2.rds.amazonaws.com:3306/travel
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qweasdQWEASD

  data:
    redis:
      port: 6379
      host: 127.0.0.1

cloud:
  aws:
    credentials:
      access-key: AKIAU3UJ5YDW5N7I7HWK
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: travel-planner-buckets

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
    org.springframework.security: DEBUG

log4j:
  logger:
    com:
      amazonaws=DEBUG:

springdoc:
  version: v1.0.0
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

secret:
  key: 68a4ef27a3f2f0f605a6781e6be34b466b5da3d11db5384218c407e99e6dcecf3361e1f6def13c78f2deb1e6e822bef2ca1c95b1166c97c5278ad81fdba4538

oauth:
  naver:
    clientId: PpeNzFLDB7WFkwi75yNH
    secret: laQWr8zOad
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com